<h1>Izuzeci</h1>
Izuzetke koristimo za promenu toka programa ukoliko dođe do pojave greške.
<br>
Kod pojave izuzetka dešava se sledeće: 
<ul>
	<li>dotadašnji deo koda se sačuva</li>
	<li>zatim se izvršava deo koda definisan funkcijom izuzetka</li>
	<li>u zavisnosti od situacije može da se nastavi izvršenje koda od mesta dokle je kod sačuvan, ili sa nekog drugog mesta u programu.</li>
</ul>
<div class = "napomena">
Izuzetke treba koristi samo u slučaju greške, ne bi trebalo da se koriste za skok na drugo mesto u kodu u određenom trenutku.
</div>
<b>Primer:</b>
<xmp class = "primer_ta">
function checkNum($number){
<?php
if($number>=1){
	throw new Exception("Vrednost mora da bude manja od 1");
}
return true;
}

checkNum(2);
?>
</xmp>
Kod iznad prijaviće grešku oblika:
<xmp class = "primer_ta">
Fatal error: Uncaught exception 'Exception'
with message 'Value must be 1 or below' in C:\webfolder\test.php:6
Stack trace: #0 C:\webfolder\test.php(12):
checkNum(28) #1 {main} thrown in C:\webfolder\test.php on line 6 
</xmp>
<h2>Try, throw, catch</h2>
Da bi izbegli grešku iz prethodnog primera, potrebno je  da napišemo odgovarajući kod koji će da hvata izbačeni izuzetak.
<br>
Izuzeci su važni, i pružaju bolju kontrolu od upravljanja greškama.
<ul>
	<li><b>try</b> - Funkcija koja sadrži izuzetak trebalo bi da bude u Try bloku. Ako se ne izbaci izuzetak program nastavlja da se izvršava normalnim tokom. Ako se izbaci izuzetak on će biti uhvaćen.</li>
	<li><b>throw</b> - pomoću komande throw ispaljujemo izuzetak. Svaka komandi throw odgovara bar jedna komanda catch.</li>
	<li><b>catch</b> - catch blok služi za hvatanje izuzetaka i pravi objekat koji čuva informacije o izuzetku.</li>
</ul>
Kada se ispali izuzetak naredni deo koda neće biti izvršen, i PHP će pronaći prvi catch blok. Ako ne postoji catch blok, program će izbaciti grešku kao u prethodnom primeru.
</xmp>
Kod iznad prijaviće grešku oblika:
<xmp class = "primer_ta">
<?php
function checkNum($number){
	if($number>=1){
	throw new Exception("Vrednost mora biti manja od 1");
	}
	return true;
}
try{
	checkNum(2);
	echo "Ako vidis ovo broj je manji od 1";
}
catch(Exception $e){
	echo "Message: ".$e->getMessage();
}
?>
</xmp>
U ovom primeru program će prijaviti grešku oblika: <br>
<span class = "primer_text">Message: Vrednost mora biti manja od 1</span>
<br><br>
U primeru iznad imali smo: <br>
<ol>
	<li>Kreirana je funkcija checkNum(). Ako je broj veći ili jednak od 1 izuzetak je ispaljen</li>
	<li>funkciju checkNum() pozivamo unutar try bloka</li>
	<li>catch blok hvata izuzetak i kreira objekat ($e) koji čuva informacije o izuzetku</li>
	<li>Poruku greške iz izuzetka pozivamo pomoću $e->getMessage()</li>
</ol>
Za pozivanje poruke greške iz izuzetka koristili smo funkciju getMessage(). Od značaja mogu biti i sledeće funkcije: 
<ul>
	<li><b>getFile()</b> - ime fajla u kome je izbačen izuzetak</li>
	<li><b>getLine()</b> - broj linije u codu, gde je izbačen izuzetak</li>
	<li><b>getTraceAsString()</b> - string koji sadrži put do mesta gde je izbačen izuzetak</li>
</ul>
<br>
Možemo kreirati sopstvenu funkciju koju pozivamo ukoliko dodje do ne uhvaćenog izuzetka. Našu funkciju aktiviramo pomoću funkcije set_exception_handler(), koja kao argument prima ime naše funkcije.
<b>Primer:</b>
<xmp class = "primer_ta">
<?php
function exception_handler($e){
	echo "Neuhvćen izuzetak: ". $e->getMessage()
}
set_exception_handler("exception_handler");
throw new Exception("Nije uhvaćen izuzetak");
echo "ovaj deo koda nije izvršen";
?>
</xmp>
<b>Zadatak:</b>
<div class = "zadatak">
Napisati program u kom dvema promenljivama dodeljujemo vrednost. Trebalo bi da izračunamo njihov količnik. Ukoliko unesemo kao delilac nula ispaliti i uhvatiti izuzetak sa porukom da je nedozvoljeno deljenje nulom.
</div>